#!/bin/bash
# Comprehensive System Review using GLM Agents
# Reviews all backend code, generates tests, and updates documentation

set -e

PROJECT_ROOT="/home/cdc/Storage/NVMe/projects/lumen"
COORDINATOR="$PROJECT_ROOT/scripts/agents/parallel_coordinator.py"
OUTPUT_SUMMARY="$PROJECT_ROOT/.agents/system_review_$(date +%Y%m%d_%H%M%S).md"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters
TOTAL_BATCHES=9
COMPLETED_BATCHES=0
FAILED_BATCHES=0

# Check if coordinator exists
if [[ ! -f "$COORDINATOR" ]]; then
    echo -e "${RED}ERROR: Coordinator script not found at:${NC}"
    echo "  $COORDINATOR"
    exit 1
fi

# Check if Python is available
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}ERROR: python3 not found${NC}"
    exit 1
fi

echo ""
echo "=========================================="
echo "   LUMEN SYSTEM COMPREHENSIVE REVIEW"
echo "=========================================="
echo ""
echo "Total batches to run: $TOTAL_BATCHES"
echo "Output will be saved to:"
echo "  $OUTPUT_SUMMARY"
echo ""
echo "This will take approximately 15-20 minutes..."
echo ""
echo "Press Ctrl+C to cancel"
sleep 2
echo ""
echo "Starting reviews..."
echo ""

# Function to run review batch
run_review_batch() {
    local batch_num=$1
    local name=$2
    local request=$3

    echo ""
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}[$batch_num/$TOTAL_BATCHES] $name${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo "Request: $request"
    echo ""
    echo "Running GLM agents... (this may take 2-5 minutes)"
    echo ""

    # Run coordinator and capture output
    set +e  # Temporarily disable exit on error
    PROPOSAL=$(python3 "$COORDINATOR" "$request" 2>&1 | tee /tmp/coordinator_output.log | tail -1)
    EXIT_CODE=$?
    set -e

    echo ""

    if [[ $EXIT_CODE -eq 0 ]] && [[ -f "$PROPOSAL" ]]; then
        echo -e "${GREEN}✓ [$name] COMPLETED${NC}"
        echo "$PROPOSAL" >> "$OUTPUT_SUMMARY.proposals"
        COMPLETED_BATCHES=$((COMPLETED_BATCHES + 1))
    else
        echo -e "${RED}✗ [$name] FAILED${NC}"
        echo "Error output:"
        tail -20 /tmp/coordinator_output.log
        FAILED_BATCHES=$((FAILED_BATCHES + 1))
        echo ""
        echo "Continuing with next batch..."
    fi

    echo ""
    echo -e "${YELLOW}Progress: $COMPLETED_BATCHES completed, $FAILED_BATCHES failed${NC}"
    echo ""

    # Add delay between batches to avoid rate limiting on FREE tier
    if [[ $batch_num -lt $TOTAL_BATCHES ]]; then
        echo "Waiting 10 seconds to avoid rate limits..."
        sleep 10
    fi
}

# Create summary header
cat > "$OUTPUT_SUMMARY" << EOF
# Lumen System Review - $(date +%Y-%m-%d)

Generated by: review_entire_system.sh
Started: $(date +%Y-%m-%d\ %H:%M:%S)

## Review Scope

This comprehensive review covers:
- Backend API endpoints (security, performance, best practices)
- Backend services (business logic, error handling)
- Backend models (data integrity, relationships)
- Storage and caching (Redis, local storage, image processing)
- Security vulnerabilities (OWASP Top 10, injection attacks, auth issues)
- Frontend components (Glassmorphism library adherence, accessibility)
- Test coverage gaps

## Batches Executed

EOF

# Batch 1: Vulnerability Scan
run_review_batch 1 "Vulnerability Scan" \
    'review "OWASP Top 10 vulnerabilities, SQL injection, XSS, CSRF, insecure dependencies, hardcoded secrets" backend/app/api/endpoints/auth.py backend/app/services/user_service_fixed.py backend/app/database/connection.py'

# Batch 2: Critical Auth & Security
run_review_batch 2 "Auth Security" \
    'review "authentication vulnerabilities, authorization bypasses, session management, rate limiting, brute force protection" backend/app/api/endpoints/auth.py backend/app/auth_middleware.py'

# Batch 3: API Endpoints
run_review_batch 3 "API Review" \
    'review "security, error handling, validation" backend/app/api/endpoints/monitoring.py'

# Batch 4: Services Layer
run_review_batch 4 "Services Review" \
    'review "business logic, error handling, performance" backend/app/services/photo_service_v2.py backend/app/services/location_service.py backend/app/services/id_management_service.py'

# Batch 5: Storage & Caching
run_review_batch 5 "Storage Review" \
    'review "performance, error handling, resource management" backend/app/storage/redis_cache.py backend/app/storage/local_storage.py backend/app/storage/image_processor.py'

# Batch 6: Database Models
run_review_batch 6 "Models Review" \
    'review "data integrity, relationships, validation" backend/app/models/relationships.py backend/app/models/lookup_tables.py'

# Batch 7: Frontend Components - Glassmorphism Library Adherence
run_review_batch 7 "Frontend Glassmorphism Review" \
    'review "adherence to Glassmorphism component library, proper use of glass-base/glass-interactive classes, CSS variables usage, accessibility, responsive design" frontend/js/modules/ui.js frontend/js/modules/upload.js frontend/css/glassmorphism-core.css'

# Batch 8: Generate Missing Tests (parallel)
run_review_batch 8 "Test Generation" \
    'test backend/app/services/photo_service_v2.py AND test backend/app/storage/image_processor.py AND test backend/app/api/endpoints/auth.py'

# Batch 9: Documentation Updates
run_review_batch 9 "Documentation" \
    'docs AND search "FastAPI authentication best practices" AND search "Redis caching patterns for photo apps"'

# Complete summary
# Count proposals before deleting temp file
PROPOSAL_COUNT=0
if [[ -f "$OUTPUT_SUMMARY.proposals" ]]; then
    PROPOSAL_COUNT=$(wc -l < "$OUTPUT_SUMMARY.proposals")
fi

cat >> "$OUTPUT_SUMMARY" << EOF

## Results Summary

Total batches: 9
Proposals generated: $PROPOSAL_COUNT
Completed: $COMPLETED_BATCHES
Failed: $FAILED_BATCHES

## Next Steps

1. Review proposals in Claude Code:
   - Read .agents/coordinated/proposal_*.json files
   - Apply safe changes (tests, docs)
   - Review risky changes (code modifications)

2. Address critical security issues first:
   - Check authentication vulnerabilities
   - Review rate limiting implementation
   - Validate input sanitization

3. Run test suite after applying changes:
   - pytest backend/tests/ -v
   - Check coverage gaps

## Proposal Files

EOF

if [[ -f "$OUTPUT_SUMMARY.proposals" ]]; then
    cat "$OUTPUT_SUMMARY.proposals" >> "$OUTPUT_SUMMARY"
    rm "$OUTPUT_SUMMARY.proposals"
fi

echo ""
echo "=========================================="
echo "         REVIEW COMPLETE"
echo "=========================================="
echo ""
echo -e "${GREEN}Completed batches: $COMPLETED_BATCHES / $TOTAL_BATCHES${NC}"
if [[ $FAILED_BATCHES -gt 0 ]]; then
    echo -e "${RED}Failed batches: $FAILED_BATCHES${NC}"
fi
echo ""
echo "Summary saved to:"
echo "  $OUTPUT_SUMMARY"
echo ""
echo "Proposals generated: $PROPOSAL_COUNT"
echo ""
echo "View all findings:"
echo "  1. Read summary: cat $OUTPUT_SUMMARY"
echo "  2. Process proposals: python3 scripts/agents/process_proposals.py summary $(date +%Y%m%d)"
echo "  3. View specific output: cat .agents/output/TIMESTAMP/1_review.md"
echo ""
echo "Proposal locations listed in summary file above."
echo ""
if [[ $FAILED_BATCHES -gt 0 ]]; then
    echo -e "${YELLOW}WARNING: Some batches failed. Check coordinator output above.${NC}"
    echo ""
fi
